language: go

go:
- 1.14

script:
  - go test -v ./...
  - go build

after_success:
- |-
  if [[ "$TRAVIS_TAG" != "" ]]; then
    curl -H "Content-Type: application/json" --data '{"source_type": "Tag", "source_name": "'$TRAVIS_TAG'"}' -X POST https://registry.hub.docker.com/u/sylr/alertmanager-splunkbot/trigger/$DOCKERHUB_TRIGGER_TOKEN/
  fi
- |-
  if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "'$TRAVIS_BRANCH'"}' -X POST https://registry.hub.docker.com/u/sylr/alertmanager-splunkbot/trigger/$DOCKERHUB_TRIGGER_TOKEN/
  fi
